### PR TITLE
Alternative approach to lookup the content-type associated with a file

### PR DESCRIPTION
**Pull request by ofkindness**
- Detect mime type by checking the magic number of the file's buffer.  In case if lookup failed:
- Lookup the content-type associated with a file (lookup based on mime-db)
- Add tests

### CODE REVIEW

**Comment by davidmz** [comment]
Most of diff is whitespace-related. Please use eslint with the auto-fix feature on. It provides almost the same formatting for all code authors.

**Comment by ofkindness** [comment]
@davidmz done

**Comment by indeyets** [comment]
@ofkindness thanks!

1. is `file-type` better than libmagic-based `mmmagic`? Is there any comparison available?
2. we use `yarn`, not `npm`. so, please remove package-lock file

**Comment by ofkindness** [comment]
@indeyets thanks for feedback
1. Good question, I can say `file-type` works better on my file sample then `mmmagic` does definitely; also this module:
- better maintained
- more widely used
- does not require compilation 
- does not use `new` 
- and yes, it has more stars on github 💯 
2. done

**Pull request merged**
