### PR TITLE
dogstatsd statistics reporting

### PR DESCRIPTION
**Pull request by berkus**
TEMP pr for code review

### CODE REVIEW

**Comment by indeyets** [comment]
does it need some kind of configuration? will it go to void by default?

**Comment by berkus** [comment]
It's doing UDP to localhost by default. Which is exactly what is configured on micropeppa and freefeed.
The only issue I see is that it'll probably try to resolve localhost, so we might want to provide a config with `host: 127.0.0.1` instead. But not required for first test.

**Comment by indeyets** [comment]
ok. looks good to me, then.

**Comment by berkus** [comment]
Should we 1) post it directly to pepyatka, 2) merge here or 3) I can make a temporary merge just for testing?

**Comment by indeyets** [comment]
I think "here" makes most sense. Pepyatka should get bugfixes for existing featureset, but all new functionality can safely go here

**Pull request merged**
