### PR TITLE
Adds 'dev' to stop lists

### PR DESCRIPTION
**Pull request by dsumin**
Adds dev page to all the stop lists.

### CODE REVIEW

**Comment by clbn** [comment]
The list in development.js was in alphabetical order (I know because I sorted out couple weeks ago).

**Comment by clbn** [comment]
@indeyets @berkus Why do we need the other two lists?

**Comment by indeyets** [comment]
@clbn because (historically) we have separate configuration-files for different environments. it should be possible to extract common parts somewhere

**Comment by clbn** [comment]
@indeyets Or, at least, we should unify it to have the same structure. Some configs have `DEFAULT_STOP_LIST`, `defaultStopList` and `USERNAME_STOP_LIST`, some just the former one.

**Comment by berkus** [comment]
According to http://chris.beams.io/posts/git-commit/ your commit message reads as "If applied, this commit will _Adds 'dev' to stop lists_" which is impropers englishes.

**Comment by clbn** [comment]
I'd like to close this PR in favor of #55. Let me know if you think it's not OK.

**Pull request closed without merging**
