### PR TITLE
Convertation thumbnails and userpics to sRGB, auto-rotate userpics

### LINKED ISSUE #41: Convert thumbnails to sRGB
For now we lose all profile information while creating thumbnails. It is because GM's autoOrient [always strips](https://github.com/aheckmann/gm/blob/master/lib/convenience/autoOrient.js) all profiles. Therefore thumbnail of images with non-standard ICC profiles have wrong colors:

[original](https://micropeppa-media.freefeed.net/attachments/e067e14d-5c7f-4f5f-b1bf-b6a62d88ba05.jpg), [thumbnail](https://micropeppa-media.freefeed.net/attachments/thumbnails/e067e14d-5c7f-4f5f-b1bf-b6a62d88ba05.jpg)

What need to fix it:
1) Place sRGB.icm file on the server ([sRGB.zip](https://github.com/FreeFeed/freefeed-server/files/117287/sRGB.zip))
2) Replace:

``` javascript
img = img
.resize(525, 175)
.autoOrient()
.quality(95)
```

to

``` javascript
img = img
.resize(525, 175)
.profile("/path/to/sRGB.icm") // !!!
.autoOrient()
.quality(95)
```

in https://github.com/FreeFeed/freefeed-server/blob/development/app%2Fmodels%2Fattachment.js#L215

This code converts image to sRGB before strip profiles.

### PR DESCRIPTION
**Pull request by davidmz**
It closes FreeFeed/freefeed-server#41 and pepyatka/pepyatka-server#294 (userpic rotation)

### CODE REVIEW

**Comment by clbn** [comment]
> Convertation thumbnails to sRGB, closes #41

It's weird, GitHub picked up https://github.com/pepyatka/pepyatka-server/issues/41 from Pepyatka (a pretty irrelevant issue), not https://github.com/FreeFeed/freefeed-server/issues/41 from this repo.

**Comment by clbn** [comment]
@davidmz Thanks! LGTM (except for some nitpicking comments), but I haven't tested it yet, will do tomorrow.

**Comment by indeyets** [comment]
we can probably use this for tests: http://unexpected.js.org/unexpected-image/

**Comment by davidmz** [comment]
OK, I think I brought everything in order. Check it please?

**Comment by clbn** [comment]
:+1:

**Pull request closed without merging**
