### PR TITLE
User descriptions (server)

### PR DESCRIPTION
**Pull request by clbn**
See also:
- https://github.com/FreeFeed/freefeed-react-client/pull/193 — support for official React client.

### CODE REVIEW

**Comment by indeyets** [comment]
What about "old client" case? As long as client doesn't send description field in update it shouldn't be updated.

I think your code will set description to empty string in this case (I might be wrong, doing review on phone)

**Comment by clbn** [comment]
It plays fine with the old clients (see https://github.com/FreeFeed/freefeed-server/pull/33/files#diff-a4b3038d4ee7f4db64a479a6b17460a6R368).

I can add a test for this.

**Comment by indeyets** [comment]
@clbn thanks! test would be awesome

**Comment by clbn** [comment]
@indeyets Added a new test in 494c661.

**Pull request merged**
