### PR TITLE
Add initial hidden comments support

### PR DESCRIPTION
**Pull request by davidmz**
1) Add is_hidden/isHidden field to comments
2) Return comments from banned users as hidden

### CODE REVIEW

**Comment by davidmz** [comment]
I rewrote the code for the model with several types of comments hidden. Requires client support (not ready yet).

**Comment by indeyets** [comment]
@davidmz some introduction text would be welcome. anyway… some questions:

1. Do I correctly understand that `hide_type` would be always `Comment.VISIBLE` in database for now? Potentially, `Comment.DELETED` and `Comment.HIDDEN_ARCHIVED` would be written there and `Comment.HIDDEN_BANNED` never will, as it is a runtime-only value.
2. What will users of `v2` api clients be seeing until clients are aware of this update? I wonder if it should be treated as BC-break

**Comment by davidmz** [comment]
Yes, `hide_type` is 0 (=== Comment.VISIBLE) by default so all existing and new comments is in Comment.VISIBLE status. Comment.HIDDEN_BANNED is an artificial status, it's only appear in API responses and doesn't actually present in DB. Comment.DELETED and Comment.HIDDEN_ARCHIVED can exists in DB as well as future statuses that may be needed for us.

Frontend can show different placeholders for different hideType's but in all other aspects all hideType !== 0 are equal. They all are have placeholder message in `body` and post author's UID in `user_id`.

API v1 returns hideType field only for hideType !== 0 (by design of our serializers). API v2 always returns hideType.

**Comment by davidmz** [comment]
Included in #205

**Pull request closed without merging**
